from elasticsearch import Elasticsearch
from flask import Flask, request

application = Flask(__name__)
# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "AnBjQU9n8pW33gbIHTtAoEy4"

# Found in the 'Manage Deployment' page
CLOUD_ID = "e6156:dXMtY2VudHJhbDEuZ2NwLmNsb3VkLmVzLmlvJDQ5MzhiNjI4ZmE0MTRjMDE5ODcyYzBiYWJmZTUzYjI1JGYzNzUwMDQ2YzI0MTQyZmNhMThmYjg4YzM5MmMxOThl"

# Create the client instance
client = Elasticsearch(
    cloud_id=CLOUD_ID,
    basic_auth=("elastic", ELASTIC_PASSWORD)
)

@application.route('/elasticsearch', methods=['POST'])
def search():
    keyword = request.get_json().get('key')
    list = es(keyword)
    return {'code':'001', 'body':list}


def es(msg):
    # Password for the 'elastic' user generated by Elasticsearch
    ELASTIC_PASSWORD = "AnBjQU9n8pW33gbIHTtAoEy4"

    # Found in the 'Manage Deployment' page
    CLOUD_ID = "e6156:dXMtY2VudHJhbDEuZ2NwLmNsb3VkLmVzLmlvJDQ5MzhiNjI4ZmE0MTRjMDE5ODcyYzBiYWJmZTUzYjI1JGYzNzUwMDQ2YzI0MTQyZmNhMThmYjg4YzM5MmMxOThl"

    # Create the client instance
    client = Elasticsearch(
        cloud_id=CLOUD_ID,
        basic_auth=("elastic", ELASTIC_PASSWORD)
    )
    result = client.search(index="product", query={
        "bool": {
            "should": [
                {"fuzzy": {"column5": msg}},
                {"fuzzy": {"column11": msg}},
                {"fuzzy": {"column2": msg}},
                {"fuzzy": {"column4": msg}}
            ]
        }
    })
    results = result['hits']['hits']
    list = []
    for r in results:
        list.append(r['_source']['column1'])
    return {'code': '001', 'body': list}


if __name__ == '__main__':
    application.run(port=8000, host='0.0.0.0')